// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of thing an event records. `ToolResult` is split out from `ToolUse`
 * so the detector can pair a call with its outcome (for error-streak and
 * repeated-action detection).
 */
export type EventKind = "run_start" | "run_end" | "assistant" | "user" | "tool_use" | "tool_result" | "thinking" | "output" | "error" | "token_usage" | "stop";
