// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verdict } from "./Verdict.js";

/**
 * The response body of `POST /ingest`: the correlated run and the daemon's
 * current verdict on it. `runId` is `None` only when the payload carried no
 * session id to correlate. Exported to the SDK via `ts-rs`.
 */
export type IngestResponse = { 
/**
 * The run this payload was attributed to (`None` if uncorrelatable).
 */
runId: string | null, 
/**
 * The daemon's verdict — `ok`/`warn` for observed runs.
 */
verdict: Verdict, };
