// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventKind } from "./EventKind.js";
import type { Source } from "./Source.js";
import type { ToolStatus } from "./ToolStatus.js";

/**
 * One normalized event. Every surface emits this shape; the store, detector,
 * and dashboard only ever see `LoopEvent`.
 */
export type LoopEvent = { 
/**
 * The run this event belongs to.
 */
runId: string, 
/**
 * Which surface produced it.
 */
source: Source, 
/**
 * What kind of event it is.
 */
kind: EventKind, 
/**
 * Tool name, for `ToolUse`/`ToolResult`.
 */
tool: string | null, 
/**
 * Stable hash of the tool's input args — feeds repeated-action / oscillation
 * detection. The detector compares hashes; the SDK only displays it.
 */
toolInputHash: bigint | null, 
/**
 * Outcome of a tool call (on `ToolResult`) — feeds error-streak detection.
 */
toolStatus: ToolStatus | null, 
/**
 * The agent turn number this event occurred in (see `ARCHITECTURE.md §8`).
 */
iteration: number | null, 
/**
 * Input tokens reported for this event, when available.
 */
tokensIn: number | null, 
/**
 * Output tokens reported for this event, when available.
 */
tokensOut: number | null, 
/**
 * Cost in USD — agent-reported when available, else computed via `pricing`.
 */
costUsd: number | null, 
/**
 * Free-text payload (assistant text, thinking, error message, …).
 */
text: string | null, 
/**
 * Sub-agent / sidechain attribution (CC `parent_tool_use_id` /
 * transcript `isSidechain`) so sub-agents don't masquerade as top-level.
 */
parentToolUseId: string | null, 
/**
 * Event timestamp (Unix epoch milliseconds).
 */
ts: bigint, };
