// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What loopd does when a cap or detector trips. Default `Warn` keeps governance
 * flag-only until the user explicitly opts into pause/kill. Carries a `TS`
 * derive because it also rides on the wire as a per-run override on `Run`.
 */
export type OnTrip = "warn" | "notify" | "pause" | "kill";
