// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunReason } from "./RunReason.js";
import type { RunStatus } from "./RunStatus.js";

/**
 * The aggregate view of a single agent loop, rolled up from its events plus
 * lifecycle metadata. One row per loop in the store.
 */
export type Run = { 
/**
 * Unique id (see [`new_run_id`]).
 */
runId: string, 
/**
 * Human-readable label (defaults to the run id).
 */
label: string, 
/**
 * Which adapter drives this run (`claude`, `codex`, …).
 */
agent: string, 
/**
 * Working directory the agent runs in.
 */
cwd: string, 
/**
 * Lifecycle state.
 */
status: RunStatus, 
/**
 * The task text — needed to retry/resume the loop.
 */
prompt: string, 
/**
 * OS process id, when loopd owns the process (Mode A).
 */
pid: number | null, 
/**
 * CC `session_id` / Codex `thread_id` — enables native resume (= pause) and
 * correlates Mode-B hook and transcript events to one run.
 */
agentSessionId: string | null, 
/**
 * The model the agent reported using.
 */
model: string | null, 
/**
 * Current iteration (agent turn) count.
 */
iteration: number, 
/**
 * Resolved cumulative cost in USD (agent-reported or computed).
 */
costUsd: number, 
/**
 * Cumulative input tokens.
 */
tokensIn: number, 
/**
 * Cumulative output tokens.
 */
tokensOut: number, 
/**
 * Process exit code, when known.
 */
exitCode: number | null, 
/**
 * Why this run exists.
 */
runReason: RunReason, 
/**
 * Sub-agent / retry lineage — the run this one derives from.
 */
parentRunId: string | null, 
/**
 * Git branch (populated read-only from `gitBranch`).
 */
branch: string | null, 
/**
 * Worktree path — reserved for v2 (worktree isolation is out of v1).
 */
worktreePath: string | null, 
/**
 * When the run started (Unix epoch ms).
 */
startedAt: bigint, 
/**
 * When the run ended (Unix epoch ms), if it has.
 */
endedAt: bigint | null, 
/**
 * Timestamp of the most recent event for this run.
 */
lastEventAt: bigint, 
/**
 * Timestamp of the most recent write to this row.
 */
updatedAt: bigint, 
/**
 * Detector flags currently raised on this run.
 */
flags: Array<string>, 
/**
 * Whether a kill has been requested (acted on by the supervisor).
 */
killRequested: boolean, 
/**
 * Whether loopd owns the process. `false` = observed (read-only): on-trip
 * actions clamp to `notify` since there's no process to act on.
 */
owned: boolean, };
