// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a run exists. `Retry` (v1) creates a *new* run with the same `prompt`,
 * `run_reason = Retry`, and `parent_run_id` pointing at the original.
 */
export type RunReason = "user_run" | "retry" | "observed" | "sdk";
