// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which ingestion surface produced an event. Lets the detector and dedup logic
 * reason about provenance (e.g. transcript is canonical for tokens; hooks are
 * low-latency liveness — see `ARCHITECTURE.md §4`).
 */
export type Source = "supervisor" | "hook" | "transcript" | "sdk";
