// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of a tool call, assigned when a `ToolResult` is paired with its
 * `ToolUse`. Drives error-streak detection. Mirrors vibe-kanban's `ToolStatus`.
 */
export type ToolStatus = "ok" | "error" | "denied" | "timed_out";
