// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The daemon's verdict on a run, returned by `POST /ingest`. This is the
 * enforcement return channel (ARCHITECTURE §4): a Mode-B hook reads it for
 * liveness, and the Phase-9 SDK's `.check()` throws/halts under `pause`/`kill`.
 * Mode B can only ever yield `ok`/`warn` (observed runs are read-only and their
 * on-trip action clamps to `notify`); `pause`/`kill` are reserved for owned SDK
 * runs. Modeled now so the wire shape is stable before the SDK consumes it.
 */
export type Verdict = "ok" | "warn" | "pause" | "kill";
